version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: panmin.me
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
